### ISSUE TITLE
vue cli 3 + webpack + IE11

### ISSUE THREAD

**Issue by maulpets** [BenAHammond/vue-anime#7]
i am getting this error whenever i try and include this on IE 11

SCRIPT1003: Expected ':'

It is causing nothing to render.  When i remove 
```
import VueAnime from 'vue-animejs';
Vue.use(VueAnime)
```
everything works fine

**Comment by BenAHammond** [comment]
I'm using ES6 for this, its likely not fully compatible with IE.

I'll push up a fix.

**Comment by maulpets** [comment]
you're the man.  i should use babel on my other dependencies but idk if im a big fan of vue cli 3.   i think i might be the only person that wants their webpack config file back.

**Comment by BenAHammond** [comment]
I've pushed up a branch but don't have the right IE to test this.

Can you pull down this branch and test it out?

https://github.com/BenAHammond/vue-anime/tree/ISSUE_7

**Comment by maulpets** [comment]
still getting the same error on this line
`/***/ "./node_modules/vue-animejs/index.js":
/*!*******************************************!*\
  !*** ./node_modules/vue-animejs/index.js ***!
  \*******************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

eval("\nconst anime = __webpack_require__(/*! animejs */ \"./node_modules/animejs/anime.min.js\");\n\nfunction install (Vue) {\n  Vue.directive('anime', {\n    bind(targets, binding) {\n      const opts = Object.assign({}, binding.value, { targets })\n      anime(opts);\n    }\n  })\n  Vue.prototype.$anime = anime;\n}\n\nmodule.exports = {\n  install\n};\n//# sourceURL=[module]\n//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiLi9ub2RlX21vZHVsZXMvdnVlLWFuaW1lanMvaW5kZXguanMuanMiLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9ub2RlX21vZHVsZXMvdnVlLWFuaW1lanMvaW5kZXguanM/MDFlOCJdLCJzb3VyY2VzQ29udGVudCI6WyJcbmNvbnN0IGFuaW1lID0gcmVxdWlyZSgnYW5pbWVqcycpO1xuXG5mdW5jdGlvbiBpbnN0YWxsIChWdWUpIHtcbiAgVnVlLmRpcmVjdGl2ZSgnYW5pbWUnLCB7XG4gICAgYmluZCh0YXJnZXRzLCBiaW5kaW5nKSB7XG4gICAgICBjb25zdCBvcHRzID0gT2JqZWN0LmFzc2lnbih7fSwgYmluZGluZy52YWx1ZSwgeyB0YXJnZXRzIH0pXG4gICAgICBhbmltZShvcHRzKTtcbiAgICB9XG4gIH0pXG4gIFZ1ZS5wcm90b3R5cGUuJGFuaW1lID0gYW5pbWU7XG59XG5cbm1vZHVsZS5leHBvcnRzID0ge1xuICBpbnN0YWxsXG59O1xuIl0sIm1hcHBpbmdzIjoiQUFBQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTsiLCJzb3VyY2VSb290IjoiIn0=\n//# sourceURL=webpack-internal:///./node_modules/vue-animejs/index.js\n");`

**Comment by maulpets** [comment]
still getting the same error on this line

```
/***/ "./node_modules/vue-animejs/index.js":
/*!*******************************************!*\
  !*** ./node_modules/vue-animejs/index.js ***!
  \*******************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

eval("\nconst anime = __webpack_require__(/*! animejs */ \"./node_modules/animejs/anime.min.js\");\n\nfunction install (Vue) {\n  Vue.directive('anime', {\n    bind(targets, binding) {\n      const opts = Object.assign({}, binding.value, { targets })\n      anime(opts);\n    }\n  })\n  Vue.prototype.$anime = anime;\n}\n\nmodule.exports = {\n  install\n};\n//# sourceURL=[module]\n//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiLi9ub2RlX21vZHVsZXMvdnVlLWFuaW1lanMvaW5kZXguanMuanMiLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9ub2RlX21vZHVsZXMvdnVlLWFuaW1lanMvaW5kZXguanM/MDFlOCJdLCJzb3VyY2VzQ29udGVudCI6WyJcbmNvbnN0IGFuaW1lID0gcmVxdWlyZSgnYW5pbWVqcycpO1xuXG5mdW5jdGlvbiBpbnN0YWxsIChWdWUpIHtcbiAgVnVlLmRpcmVjdGl2ZSgnYW5pbWUnLCB7XG4gICAgYmluZCh0YXJnZXRzLCBiaW5kaW5nKSB7XG4gICAgICBjb25zdCBvcHRzID0gT2JqZWN0LmFzc2lnbih7fSwgYmluZGluZy52YWx1ZSwgeyB0YXJnZXRzIH0pXG4gICAgICBhbmltZShvcHRzKTtcbiAgICB9XG4gIH0pXG4gIFZ1ZS5wcm90b3R5cGUuJGFuaW1lID0gYW5pbWU7XG59XG5cbm1vZHVsZS5leHBvcnRzID0ge1xuICBpbnN0YWxsXG59O1xuIl0sIm1hcHBpbmdzIjoiQUFBQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTsiLCJzb3VyY2VSb290IjoiIn0=\n//# sourceURL=webpack-internal:///./node_modules/vue-animejs/index.js\n");
```

**Comment by BenAHammond** [comment]
Ah I think that's actually related to the sourcemaps in your webpack'd code.

Try disabling sourcemaps.

**Comment by maulpets** [comment]
i took your index.js dropped into babel and MAGIC!! 

Works as intended on IE

```
'use strict';

var anime = require('animejs');

function install(Vue) {
  Vue.directive('anime', {
    bind: function bind(targets, binding) {
      var opts = Object.assign({}, binding.value, { targets: targets });
      anime(opts);
    }
  });
  Vue.prototype.$anime = anime;
}

module.exports = {
  install: install
};
```

**Comment by BenAHammond** [comment]
I guess that original object usage is still ES6. Boy, this really takes me back.
